displayName: Azure AD access validator
type: middleware

import: github.com/sanderPostma/traefik-validate-jwt

summary: 'Authenticates against Azure app registrations by validating the JWT bearer token and checks if the configuration has a tenantId & app/clientId filter match before the request is forwarded to the target service.'

testData:
  filters:
    - tenantId: e2a42b2f-7460-4499-afc2-425315ef058a
      appIds: [ "4fc07429-f068-47fa-b5cd-5b460ec8529d" ]
  TenantIdFilters:
    - TenantId: e2a42b2f-7460-4499-afc2-425315ef058a
      AppIds: [ "4fc07429-f068-47fa-b5cd-5b460ec8529d" ]
